# pandas 그룹분석
## 1주차 2일차 - 07/16

첨부된 PowerPoint 파일에서 모든 예시 코드를 추출하여 주피터 노트북에서 바로 실행할 수 있도록 정리했습니다. 각 섹션별로 코드를 구성하여 학생들이 순차적으로 학습할 수 있도록 하였습니다.

### 0. 라이브러리 및 데이터 준비

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# 한글 폰트 설정 (선택사항)
plt.rcParams['font.family'] = 'DejaVu Sans'

In [2]:
# 데이터 로드
df = sns.load_dataset('tips')
print("데이터 기본 정보:")
display(df.head())
print(f"데이터 크기: {df.shape}")
print(f"컬럼 정보: {df.columns.tolist()}")

데이터 기본 정보:

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

데이터 크기: (244, 7)
컬럼 정보: ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

### 1. 멀티 인덱스 기본 개념
#### 1-1. 멀티 인덱스 생성 - 기본 방법

In [3]:
# 멀티 인덱스 생성 예시 1
values = [[1,2,3], [4,5,6], [7,8,9], [10,11,12],
          [13,14,15], [16,17,18], [19,20,21]]

df_multi = pd.DataFrame(values,
                  columns=['col1', 'col2', 'col3'],
                  index=[['row1','row1','row2','row2',
                          'row2','row3','row3'],
                         ['val1','val2','val1','val2',
                          'val3','val2','val3']])

print("멀티 인덱스 DataFrame:")
df_multi

멀티 인덱스 DataFrame:

           col1  col2  col3
row1 val1     1     2     3
     val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18
     val3    19    20    21

#### 1-2. from_tuples()를 사용한 멀티 인덱스 생성

In [4]:
# 행 멀티 인덱스 생성
index_tuples = [('row1', 'val1'), ('row1', 'val2'),
                ('row2', 'val1'), ('row2', 'val2'),
                ('row2', 'val3'), ('row3', 'val2'),
                ('row3', 'val3')]

values = [[1,2,3], [4,5,6], [7,8,9], [10,11,12],
          [13,14,15], [16,17,18], [19,20,21]]

index = pd.MultiIndex.from_tuples(index_tuples)
df_row_multi = pd.DataFrame(values,
                  columns=['col1', 'col2','col3'],
                  index = index)

print("행 멀티 인덱스:")
df_row_multi

행 멀티 인덱스:

           col1  col2  col3
row1 val1     1     2     3
     val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18
     val3    19    20    21

#### 1-3. 열 멀티 인덱스 생성

In [5]:
# 열 멀티 인덱스 생성
values = [[1,2,3], [4,5,6], [7,8,9], [10,11,12],
          [13,14,15], [16,17,18], [19,20,21]]

df_col_multi = pd.DataFrame(values,
                columns=[['A','B','C'],
                         ['col1', 'col1', 'col2']] ,
                index = index )

print("열 멀티 인덱스:")
df_col_multi

열 멀티 인덱스:

             A    B    C
          col1 col1 col2
row1 val1    1    2    3
     val2    4    5    6
row2 val1    7    8    9
     val2   10   11   12
     val3   13   14   15
row3 val2   16   17   18
     val3   19   20   21

#### 1-4. Tips 데이터로 멀티 인덱스 생성

In [6]:
# tips 데이터로 멀티 인덱스 생성 및 확인
df_multi_tips = df.set_index(['smoker', 'sex', 'day'])
print("멀티 인덱스 생성 후:")
display(df_multi_tips.head())
print(f"인덱스 레벨 수: {df_multi_tips.index.nlevels}")
print(f"인덱스 이름들: {df_multi_tips.index.names}")

멀티 인덱스 생성 후:

                   total_bill   tip    time  size
smoker sex    day
No     Female Sun       16.99  1.01  Dinner     2
       Male   Sun       10.34  1.66  Dinner     3
              Sun       21.01  3.50  Dinner     3
              Sun       23.68  3.31  Dinner     2
       Female Sun       24.59  3.61  Dinner     4

인덱스 레벨 수: 3
인덱스 이름들: ['smoker', 'sex', 'day']

#### 1-6. 멀티 인덱스 데이터 선택

In [7]:
# 멀티 인덱스에서 데이터 선택
print("1. 튜플로 특정 그룹 선택:")
display(df_multi_tips.loc[('Yes', 'Male')].head())

1. 튜플로 특정 그룹 선택:

     total_bill   tip    time  size
day
Sat       38.01  3.00  Dinner     4
Sat       11.24  1.76  Dinner     2
Sat       20.29  3.21  Dinner     2
Sat       13.81  2.00  Dinner     2
Sat       11.02  1.98  Dinner     2

In [8]:
print("\n2. xs()로 특정 레벨 선택:")
display(df_multi_tips.xs('Male', level='sex').head())

2. xs()로 특정 레벨 선택:

            total_bill   tip    time  size
smoker day
No     Sun       10.34  1.66  Dinner     3
       Sun       21.01  3.50  Dinner     3
       Sun       23.68  3.31  Dinner     2
       Sun       25.29  4.71  Dinner     4
       Sun        8.77  2.00  Dinner     2

In [9]:
print("\n3. 부분 선택 (상위 레벨만 지정):")
smoker_data = df_multi_tips.loc['Yes']
display(smoker_data.head())

3. 부분 선택 (상위 레벨만 지정):

          total_bill   tip    time  size
sex  day
Male Sat       38.01  3.00  Dinner     4
     Sat       11.24  1.76  Dinner     2
     Sat       20.29  3.21  Dinner     2
     Sat       13.81  2.00  Dinner     2
     Sat       11.02  1.98  Dinner     2

### 1-7. 멀티 인덱스 조작 함수

In [10]:
# swaplevel() 함수
print("1. swaplevel() - 레벨 순서 바꾸기:")
df_swapped_pos = df_multi_tips.swaplevel(0, 2)  # smoker와 day 레벨 교체
print("위치로 레벨 교체:")
display(df_swapped_pos.head())

1. swaplevel() - 레벨 순서 바꾸기:
위치로 레벨 교체:

                   total_bill   tip    time  size
day sex    smoker
Sun Female No           16.99  1.01  Dinner     2
    Male   No           10.34  1.66  Dinner     3
           No           21.01  3.50  Dinner     3
           No           23.68  3.31  Dinner     2
    Female No           24.59  3.61  Dinner     4

In [11]:
df_swapped_name = df_multi_tips.swaplevel('smoker', 'day')
print("\n이름으로 레벨 교체:")
display(df_swapped_name.head())

이름으로 레벨 교체:

                   total_bill   tip    time  size
day sex    smoker
Sun Female No           16.99  1.01  Dinner     2
    Male   No           10.34  1.66  Dinner     3
           No           21.01  3.50  Dinner     3
           No           23.68  3.31  Dinner     2
    Female No           24.59  3.61  Dinner     4

In [12]:
# reorder_levels() 함수
print("\n2. reorder_levels() - 전체 레벨 순서 재정렬:")
df_reordered = df_multi_tips.reorder_levels(['day', 'smoker', 'sex'])
print("레벨 순서 재정렬 (day → smoker → sex):")
display(df_reordered.head())

2. reorder_levels() - 전체 레벨 순서 재정렬:
레벨 순서 재정렬 (day → smoker → sex):

                   total_bill   tip    time  size
day smoker sex
Sun No     Female       16.99  1.01  Dinner     2
           Male         10.34  1.66  Dinner     3
           Male         21.01  3.50  Dinner     3
           Male         23.68  3.31  Dinner     2
           Female       24.59  3.61  Dinner     4

In [13]:
# droplevel() 함수
print("\n3. droplevel() - 특정 레벨 제거:")
df_dropped_name = df_multi_tips.droplevel('day')
print("day 레벨 제거:")
display(df_dropped_name.head())

3. droplevel() - 특정 레벨 제거:
day 레벨 제거:

               total_bill   tip    time  size
smoker sex
No     Female       16.99  1.01  Dinner     2
       Male         10.34  1.66  Dinner     3
       Male         21.01  3.50  Dinner     3
       Male         23.68  3.31  Dinner     2
       Female       24.59  3.61  Dinner     4

### 2. 그룹 분석 (GroupBy)
#### 2-1. 기본 그룹 분석

In [14]:
# SAC 패턴 단계별 이해
print("=== Split-Apply-Combine 패턴 ===")

# 1. Split: 데이터 분할 과정 시각화
grouped = df.groupby('smoker')
print("1. Split - 그룹 분할:")
print(f"전체 그룹 수: {grouped.ngroups}")
print(f"그룹 키: {list(grouped.groups.keys())}")
print(f"각 그룹 크기: {grouped.size()}")

# 2. Apply: 각 그룹에 함수 적용
print("\n2. Apply - 함수 적용:")
for name, group in grouped:
    print(f"{name} 그룹 평균 팁: {group['tip'].mean():.2f}")

# 3. Combine: 결과 결합
print("\n3. Combine - 결과 결합:")
result = grouped['tip'].mean()
print(result)

=== Split-Apply-Combine 패턴 ===
1. Split - 그룹 분할:
전체 그룹 수: 2
그룹 키: ['Yes', 'No']
각 그룹 크기: smoker
Yes     93
No     151
dtype: int64

2. Apply - 함수 적용:
Yes 그룹 평균 팁: 3.01
No 그룹 평균 팁: 2.99

3. Combine - 결과 결합:
smoker
Yes    3.008710
No     2.991854
Name: tip, dtype: float64

#### 2-2. 다양한 집계 함수 활용

In [15]:
# 기본 집계 함수들
print("기본 집계 함수들:")
print("합계:", df.groupby('smoker')['tip'].sum())
print("평균:", df.groupby('smoker')['tip'].mean())
print("중앙값:", df.groupby('smoker')['tip'].median())
print("최소값:", df.groupby('smoker')['tip'].min())
print("최대값:", df.groupby('smoker')['tip'].max())
print("개수:", df.groupby('smoker')['tip'].count())
print("표준편차:", df.groupby('smoker')['tip'].std())

# 다중 그룹화
print("\n다중 그룹화:")
gb = df.groupby(['smoker', 'time'])
out = gb[['total_bill', 'tip']].agg('mean')
print(out)

기본 집계 함수들:
합계: smoker
Yes    279.81
No     451.77
Name: tip, dtype: float64
평균: smoker
Yes    3.008710
No     2.991854
Name: tip, dtype: float64
중앙값: smoker
Yes    3.00
No     2.74
Name: tip, dtype: float64
최소값: smoker
Yes    1.0
No     1.0
Name: tip, dtype: float64
최대값: smoker
Yes    10.0
No      9.0
Name: tip, dtype: float64
개수: smoker
Yes     93
No     151
Name: tip, dtype: int64
표준편차: smoker
Yes    1.401468
No     1.377190
Name: tip, dtype: float64

다중 그룹화:
               total_bill       tip
smoker time
Yes    Lunch    17.399130  2.834348
       Dinner   21.859429  3.066000
No     Lunch    17.050889  2.673778
       Dinner   20.095660  3.126887

#### 2-3. 고급 집계 함수

In [16]:
# 다양한 집계 함수 한 번에 적용
grouped = df.groupby('day').agg({
    'total_bill': ['sum', 'mean', 'min', 'max'],
    'tip': ['mean', 'std', 'count']
})
print("다양한 집계 함수 적용:")
display(grouped)

다양한 집계 함수 적용:

     total_bill                               tip
            sum       mean   min    max      mean       std count
day
Thur    1096.33  17.682742  7.51  43.11  2.771452  1.240223    62
Fri      325.88  17.151579  5.75  40.17  2.734737  1.019577    19
Sat     1778.40  20.441379  3.07  50.81  2.993103  1.631014    87
Sun     1627.16  21.410000  7.25  48.17  3.255132  1.234880    76

In [17]:
# Named Aggregation
result = df.groupby('smoker').agg(
    total_bill_sum=('total_bill', 'sum'),
    tip_avg=('tip', 'mean'),
    tip_std=('tip', 'std')
)
print("\nNamed Aggregation:")
display(result)

Named Aggregation:

        total_bill_sum   tip_avg   tip_std
smoker
Yes            1930.34  3.008710  1.401468
No             2897.43  2.991854  1.377190

In [18]:
# reset_index로 인덱스 정리
grouped = df.groupby(['day', 'sex'])['tip'].mean()
grouped_reset = grouped.reset_index()
print("\nreset_index 사용:")
display(grouped_reset)

reset_index 사용:

    day     sex       tip
0  Thur    Male  2.980333
1  Thur  Female  2.575625
2   Fri    Male  2.693000
3   Fri  Female  2.781111
4   Sat    Male  3.083898
5   Sat  Female  2.801786
6   Sun    Male  3.220345
7   Sun  Female  3.367222

#### 2-4. 고급 그룹화 함수 - transform() 함수

In [19]:
# transform() 함수 활용
print("transform() 함수 활용:")

# 그룹별 평균 대비 비율
df['tip_ratio_to_group_mean'] = df.groupby('day')['tip'].transform(lambda x: x / x.mean())

# 그룹별 표준화 (Z-score)
df['tip_zscore'] = df.groupby('day')['tip'].transform(lambda x: (x - x.mean()) / x.std())

# 그룹별 순위
df['tip_rank_in_day'] = df.groupby('day')['tip'].transform('rank')

# 그룹별 누적합
df['tip_cumsum_in_day'] = df.groupby('day')['tip'].transform('cumsum')

display(df[['day', 'tip', 'tip_ratio_to_group_mean', 'tip_zscore', 'tip_rank_in_day']].head(10))

transform() 함수 활용:

   day   tip  tip_ratio_to_group_mean  tip_zscore  tip_rank_in_day
0  Sun  1.01                 0.310279   -1.818097              1.0
1  Sun  1.66                 0.509964   -1.291730              6.0
2  Sun  3.50                 1.075225    0.198293             46.0
3  Sun  3.31                 1.016856    0.044432             41.0
4  Sun  3.61                 1.109018    0.287371             52.0
5  Sun  4.71                 1.446946    1.178145             64.0
6  Sun  2.00                 0.614414   -1.016399             14.5
7  Sun  3.12                 0.958487   -0.109429             38.0
8  Sun  1.96                 0.602126   -1.048791              9.0
9  Sun  3.23                 0.992279   -0.020351             40.0

In [20]:
# 결측값 처리에 transform 활용
print("\n결측값 처리:")
df_with_na = df.copy()
df_with_na.loc[0:2, 'tip'] = None
df_with_na['tip_filled'] = df_with_na.groupby('day')['tip'].transform(
    lambda x: x.fillna(x.mean())
)
display(df_with_na[['day', 'tip', 'tip_filled']].head())

결측값 처리:

   day   tip  tip_filled
0  Sun   NaN    3.304384
1  Sun   NaN    3.304384
2  Sun   NaN    3.304384
3  Sun  3.31    3.310000
4  Sun  3.61    3.610000

#### 2-4. 고급 그룹화 함수 - filter() 함수

In [21]:
# filter() 함수 활용
print("filter() 함수 활용:")

# 그룹 크기가 30개 이상인 요일만 선택
large_day_groups = df.groupby('day').filter(lambda x: len(x) >= 30)
print(f"대규모 그룹 요일 데이터 수: {len(large_day_groups)}")
print(f"포함된 요일: {large_day_groups['day'].unique()}")

filter() 함수 활용:
대규모 그룹 요일 데이터 수: 225
포함된 요일: ['Sun', 'Sat', 'Thur']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [22]:
# 평균 계산서가 20달러 이상인 요일만 선택
high_bill_days = df.groupby('day').filter(lambda x: x['total_bill'].mean() > 20)
print(f"고액 결제 요일 데이터 수: {len(high_bill_days)}")
print(f"포함된 요일: {high_bill_days['day'].unique()}")

고액 결제 요일 데이터 수: 163
포함된 요일: ['Sun', 'Sat']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [23]:
# 복합 조건 필터링
complex_filter = df.groupby('day').filter(
    lambda x: (x['total_bill'].mean() > 18) & (x['tip'].std() < 1.5)
)
print(f"복합 조건 만족 데이터 수: {len(complex_filter)}")

복합 조건 만족 데이터 수: 76

#### 2-4. 고급 그룹화 함수 - apply() 함수

In [24]:
# apply() 함수 활용
def analyze_day_performance(group):
    """요일별 성과 분석 함수"""
    result = pd.Series({
        'total_customers': len(group),
        'total_revenue': group['total_bill'].sum(),
        'avg_bill': group['total_bill'].mean(),
        'avg_tip': group['tip'].mean(),
        'tip_percentage': (group['tip'].sum() / group['total_bill'].sum()) * 100,
        'large_party_ratio': (group['size'] >= 4).mean() * 100,
        'peak_hour_sales': group[group['time'] == 'Dinner']['total_bill'].sum()
    })
    return result

In [25]:
performance_analysis = df.groupby('day').apply(analyze_day_performance).round(2)
print("요일별 성과 분석:")
display(performance_analysis)

요일별 성과 분석:

,total_customers,total_revenue,avg_bill,avg_tip,tip_percentage,large_party_ratio,peak_hour_sales
day,,,,,,,
Thur,62.0,1096.33,17.68,2.77,15.67,14.52,18.78
Fri,19.0,325.88,17.15,2.73,15.94,5.26,235.96
Sat,87.0,1778.40,20.44,2.99,14.64,16.09,1778.40
Sun,76.0,1627.16,21.41,3.26,15.20,28.95,1627.16

In [26]:
# 그룹별 상위 N개 데이터 추출
def top_n_customers(group, n=3):
    """각 그룹에서 상위 N개 고객 추출"""
    return group.nlargest(n, 'total_bill')[['total_bill', 'tip', 'size']]

In [27]:
top_customers = df.groupby('day').apply(lambda x: top_n_customers(x, 2))
print("\n요일별 상위 고객:")
display(top_customers)

요일별 상위 고객:

          total_bill    tip  size
day
Thur 197       43.11   5.00     4
     142       41.19   5.00     5
Fri  95        40.17   4.73     4
     90        28.97   3.00     2
Sat  170       50.81  10.00     3
     212       48.33   9.00     4
Sun  156       48.17   5.00     6
     182       45.35   3.50     3

### 3. 피벗 테이블
#### 3-1. 기본 피벗 테이블

In [28]:
# 기본 피벗 테이블
print("1. 기본 피벗 테이블:")
basic_pivot = df.pivot_table(
    values='tip',           # 집계할 데이터
    index='day',            # 행 기준
    columns='time',         # 열 기준
    aggfunc='mean'          # 집계 함수
)
display(basic_pivot)

1. 기본 피벗 테이블:

time     Lunch    Dinner
day
Thur  2.767705  3.000000
Fri   2.382857  2.940000
Sat        NaN  2.993103
Sun        NaN  3.255132

In [29]:
# 다중 값 집계
print("\n2. 다중 값 집계:")
multi_values = df.pivot_table(
    values=['total_bill', 'tip'],
    index='day',
    columns='time',
    aggfunc='mean',
    fill_value=0
)
display(multi_values)

2. 다중 값 집계:

           tip           total_bill
time     Lunch    Dinner      Lunch     Dinner
day
Thur  2.767705  3.000000  17.664754  18.780000
Fri   2.382857  2.940000  12.845714  19.663333
Sat   0.000000  2.993103   0.000000  20.441379
Sun   0.000000  3.255132   0.000000  21.410000

In [30]:
# 다중 집계 함수
print("\n3. 다중 집계 함수:")
multi_aggfunc = df.pivot_table(
    values='total_bill',
    index='day',
    columns='smoker',
    aggfunc=['mean', 'sum', 'count'],
    fill_value=0
)
display(multi_aggfunc)

3. 다중 집계 함수:

             mean                sum          count
smoker        Yes         No     Yes       No   Yes  No
day
Thur    19.190588  17.113111  326.24   770.09    17  45
Fri     16.813333  18.420000  252.20    73.68    15   4
Sat     21.276667  19.661778  893.62   884.78    42  45
Sun     24.120000  20.506667  458.28  1168.88    19  57

#### 3-2. 고급 피벗 테이블

In [31]:
# 총계 추가
print("총계 추가:")
with_margins = df.pivot_table(
    values='total_bill',
    index='day',
    columns='smoker',
    aggfunc='mean',
    margins=True,
    margins_name='전체'
)
display(with_margins)

총계 추가:

smoker        Yes         No         전체
day
Thur    19.190588  17.113111  17.682742
Fri     16.813333  18.420000  17.151579
Sat     21.276667  19.661778  20.441379
Sun     24.120000  20.506667  21.410000
전체      20.756344  19.188278  19.785943

In [32]:
# 다중 인덱스 피벗
print("\n다중 인덱스 피벗:")
multi_index_pivot = df.pivot_table(
    values='total_bill',
    index=['day', 'smoker'],
    columns='time',
    aggfunc='mean'
)
display(multi_index_pivot)

다중 인덱스 피벗:

time             Lunch     Dinner
day  smoker
Thur Yes     19.190588        NaN
     No      17.075227  18.780000
Fri  Yes     12.323333  19.806667
     No      15.980000  19.233333
Sat  Yes           NaN  21.276667
     No            NaN  19.661778
Sun  Yes           NaN  24.120000
     No            NaN  20.506667

In [33]:
# 조건부 피벗
print("\n조건부 피벗:")
large_party = df[df['size'] >= 4]
large_party_pivot = large_party.pivot_table(
    values='total_bill',
    index='day',
    columns='time',
    aggfunc='mean',
    fill_value=0
)
display(large_party_pivot)

조건부 피벗:

time      Lunch     Dinner
day
Thur  31.343333   0.000000
Fri    0.000000  40.170000
Sat    0.000000  29.752857
Sun    0.000000  27.707273

### 4. Stack과 Unstack
#### 4-1. Stack 함수

In [34]:
# 피벗 데이터 생성
pivot_data = df.pivot_table(
    values='tip',
    index='day',
    columns='time',
    aggfunc='mean'
)

print("원본 피벗 데이터:")
pivot_data

원본 피벗 데이터:

time     Lunch    Dinner
day
Thur  2.767705  3.000000
Fri   2.382857  2.940000
Sat        NaN  2.993103
Sun        NaN  3.255132

In [35]:
# 기본 스택 변환
print("\n1. 기본 스택 변환:")
basic_stack = pivot_data.stack()
basic_stack

1. 기본 스택 변환:

day   time
Thur  Lunch     2.767705
      Dinner    3.000000
Fri   Lunch     2.382857
      Dinner    2.940000
Sat   Dinner    2.993103
Sun   Dinner    3.255132
dtype: float64

In [36]:
# 결측값 처리 옵션
print("\n2. 결측값 처리 옵션:")
stack_with_na = pivot_data.stack(dropna=False)
print("결측값 유지:")
display(stack_with_na)

stack_without_na = pivot_data.stack(dropna=True)
print("\n결측값 제거 (기본값):")
display(stack_without_na)

2. 결측값 처리 옵션:
결측값 유지:

day   time
Thur  Lunch     2.767705
      Dinner    3.000000
Fri   Lunch     2.382857
      Dinner    2.940000
Sat   Lunch          NaN
      Dinner    2.993103
Sun   Lunch          NaN
      Dinner    3.255132
dtype: float64

결측값 제거 (기본값):

day   time
Thur  Lunch     2.767705
      Dinner    3.000000
Fri   Lunch     2.382857
      Dinner    2.940000
Sat   Dinner    2.993103
Sun   Dinner    3.255132
dtype: float64

#### 4-2. Unstack 함수

In [37]:
# 멀티 인덱스 데이터 생성
multi_index_data = df.groupby(['day', 'time'])['tip'].mean()
print("1. 멀티 인덱스 데이터:")
display(multi_index_data)

1. 멀티 인덱스 데이터:

day   time
Thur  Lunch     2.767705
      Dinner    3.000000
Fri   Lunch     2.382857
      Dinner    2.940000
Sat   Lunch          NaN
      Dinner    2.993103
Sun   Lunch          NaN
      Dinner    3.255132
Name: tip, dtype: float64

In [38]:
print("\n기본 언스택:")
basic_unstack = multi_index_data.unstack()
display(basic_unstack)

기본 언스택:

time     Lunch    Dinner
day
Thur  2.767705  3.000000
Fri   2.382857  2.940000
Sat        NaN  2.993103
Sun        NaN  3.255132

In [39]:
# 결측값 처리
print("\n2. 결측값 처리:")
unstack_filled = multi_index_data.unstack(fill_value=0)
print("결측값을 0으로 대체:")
display(unstack_filled)

2. 결측값 처리:
결측값을 0으로 대체:

time     Lunch    Dinner
day
Thur  2.767705  3.000000
Fri   2.382857  2.940000
Sat        NaN  2.993103
Sun        NaN  3.255132

In [40]:
# 3중 인덱스 데이터로 다양한 레벨 언스택
triple_index_data = df.groupby(['day', 'time', 'smoker'])['tip'].mean()
print("\n3. 3중 인덱스 데이터:")
display(triple_index_data.head())

3. 3중 인덱스 데이터:

day   time    smoker
Thur  Lunch   Yes       3.030000
              No        2.666364
      Dinner  Yes            NaN
              No        3.000000
Fri   Lunch   Yes       2.280000
Name: tip, dtype: float64

In [41]:
level_0_unstack = triple_index_data.unstack(level=0)
print("\n레벨 0 언스택:")
display(level_0_unstack.head())

레벨 0 언스택:

day                Thur       Fri       Sat       Sun
time   smoker
Lunch  Yes     3.030000  2.280000       NaN       NaN
       No      2.666364  3.000000       NaN       NaN
Dinner Yes          NaN  3.003333  2.875476  3.516842
       No      3.000000  2.750000  3.102889  3.167895

#### 4-3. Melt 함수

In [42]:
# melt() 함수 활용
sample_data = df[['day', 'total_bill', 'tip', 'size']].head(5)
print("1. 원본 데이터:")
display(sample_data)

1. 원본 데이터:

   day  total_bill   tip  size
0  Sun       16.99  1.01     2
1  Sun       10.34  1.66     3
2  Sun       21.01  3.50     3
3  Sun       23.68  3.31     2
4  Sun       24.59  3.61     4

In [43]:
# melt() 사용
melted_data = sample_data.melt(
    id_vars=['day'],
    value_vars=['total_bill', 'tip', 'size'],
    var_name='measure',
    value_name='amount'
)
print("\n2. melt() 사용:")
display(melted_data)

2. melt() 사용:

    day     measure  amount
0   Sun  total_bill   16.99
1   Sun  total_bill   10.34
2   Sun  total_bill   21.01
3   Sun  total_bill   23.68
4   Sun  total_bill   24.59
5   Sun         tip    1.01
6   Sun         tip    1.66
7   Sun         tip    3.50
8   Sun         tip    3.31
9   Sun         tip    3.61
10  Sun        size    2.00
11  Sun        size    3.00
12  Sun        size    3.00
13  Sun        size    2.00
14  Sun        size    4.00

In [44]:
# stack() 사용 (비교용)
sample_indexed = sample_data.set_index('day')
stacked_data = sample_indexed.stack().reset_index()
stacked_data.columns = ['day', 'measure', 'amount']
print("\n3. stack() 사용 (비교):")
display(stacked_data)

3. stack() 사용 (비교):

    day     measure  amount
0   Sun  total_bill   16.99
1   Sun         tip    1.01
2   Sun        size    2.00
3   Sun  total_bill   10.34
4   Sun         tip    1.66
5   Sun        size    3.00
6   Sun  total_bill   21.01
7   Sun         tip    3.50
8   Sun        size    3.00
9   Sun  total_bill   23.68
10  Sun         tip    3.31
11  Sun        size    2.00
12  Sun  total_bill   24.59
13  Sun         tip    3.61
14  Sun        size    4.00

### 5. 데이터 병합 (Merge)
#### 5-1. 기본 병합 예시

In [45]:
# 병합용 샘플 데이터 생성
data1 = {'ID': [1, 2, 3, 4, 5],
         'Name': ['John', 'Emily', 'Charlie', 'Jessica', 'Brian']}
data2 = {'ID': [1, 2, 3, 4, 6],
         'Age': [25, 30, 35, 40, 45]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print("데이터프레임 1:")
display(df1)
print("\n데이터프레임 2:")
display(df2)

데이터프레임 1:

   ID     Name
0   1     John
1   2    Emily
2   3  Charlie
3   4  Jessica
4   5    Brian

데이터프레임 2:

   ID  Age
0   1   25
1   2   30
2   3   35
3   4   40
4   6   45

In [46]:
# 다양한 조인 방식
print("\n1. Inner Join:")
inner_result = pd.merge(df1, df2, on='ID', how='inner')
display(inner_result)

1. Inner Join:

   ID     Name  Age
0   1     John   25
1   2    Emily   30
2   3  Charlie   35
3   4  Jessica   40

In [47]:
print("\n2. Left Join:")
left_result = pd.merge(df1, df2, on='ID', how='left')
display(left_result)

2. Left Join:

   ID     Name   Age
0   1     John  25.0
1   2    Emily  30.0
2   3  Charlie  35.0
3   4  Jessica  40.0
4   5    Brian   NaN

In [48]:
print("\n3. Right Join:")
right_result = pd.merge(df1, df2, on='ID', how='right')
display(right_result)

3. Right Join:

   ID     Name  Age
0   1     John   25
1   2    Emily   30
2   3  Charlie   35
3   4  Jessica   40
4   6      NaN   45

In [49]:
print("\n4. Outer Join:")
outer_result = pd.merge(df1, df2, on='ID', how='outer')
display(outer_result)

4. Outer Join:

   ID     Name   Age
0   1     John  25.0
1   2    Emily  30.0
2   3  Charlie  35.0
3   4  Jessica  40.0
4   5    Brian   NaN
5   6      NaN  45.0

#### 5-2. 고급 병합 기법

In [50]:
# 고객 정보 데이터 생성
np.random.seed(42)
customer_info = pd.DataFrame({
    'customer_id': range(1, 11),
    'name': ['John', 'Emily', 'Charlie', 'Jessica', 'Brian',
             'Sarah', 'Mike', 'Lisa', 'Tom', 'Anna'],
    'age': [25, 30, 35, 40, 45, 28, 33, 38, 42, 29],
    'city': ['Seoul', 'Busan', 'Daegu', 'Incheon', 'Gwangju',
             'Daejeon', 'Ulsan', 'Sejong', 'Suwon', 'Goyang']
})

# tips 데이터에 customer_id 추가
df_with_id = df.copy()
df_with_id['customer_id'] = np.random.randint(1, 11, len(df))

print("고객 정보:")
display(customer_info)

고객 정보:

   customer_id     name  age     city
0            1     John   25    Seoul
1            2    Emily   30    Busan
2            3  Charlie   35    Daegu
3            4  Jessica   40  Incheon
4            5    Brian   45  Gwangju
5            6    Sarah   28  Daejeon
6            7     Mike   33    Ulsan
7            8     Lisa   38   Sejong
8            9      Tom   42    Suwon
9           10     Anna   29   Goyang

In [51]:
# 다중 키 병합
restaurant_menu = pd.DataFrame({
    'day': ['Fri', 'Sat', 'Sun', 'Thur', 'Fri', 'Sat'],
    'time': ['Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch'],
    'special_menu': ['Fish', 'Steak', 'Lobster', 'Salad', 'Pasta', 'Soup'],
    'menu_price': [15.0, 25.0, 35.0, 12.0, 18.0, 10.0],
    'chef_special': [True, True, True, False, False, False]
})

print("\n레스토랑 메뉴 데이터:")
display(restaurant_menu)

레스토랑 메뉴 데이터:

    day    time special_menu  menu_price  chef_special
0   Fri   Lunch         Fish        15.0          True
1   Sat  Dinner        Steak        25.0          True
2   Sun  Dinner      Lobster        35.0          True
3  Thur   Lunch        Salad        12.0         False
4   Fri  Dinner        Pasta        18.0         False
5   Sat   Lunch         Soup        10.0         False

In [52]:
# 다중 키로 병합
multi_key_result = pd.merge(
    df[['day', 'time', 'total_bill', 'tip']].head(10),
    restaurant_menu,
    on=['day', 'time'],
    how='left'
)
print("\n다중 키 병합 결과:")
display(multi_key_result)

다중 키 병합 결과:

   day    time  total_bill   tip special_menu  menu_price  chef_special
0  Sun  Dinner       16.99  1.01      Lobster        35.0          True
1  Sun  Dinner       10.34  1.66      Lobster        35.0          True
2  Sun  Dinner       21.01  3.50      Lobster        35.0          True
3  Sun  Dinner       23.68  3.31      Lobster        35.0          True
4  Sun  Dinner       24.59  3.61      Lobster        35.0          True
5  Sun  Dinner       25.29  4.71      Lobster        35.0          True
6  Sun  Dinner        8.77  2.00      Lobster        35.0          True
7  Sun  Dinner       26.88  3.12      Lobster        35.0          True
8  Sun  Dinner       15.04  1.96      Lobster        35.0          True
9  Sun  Dinner       14.78  3.23      Lobster        35.0          True

#### 5-3. 서로 다른 키 이름 병합

In [53]:
# 다른 키 이름 데이터 생성
weather_data = pd.DataFrame({
    'date': ['Fri', 'Sat', 'Sun', 'Thur'],
    'weather': ['Sunny', 'Rainy', 'Sunny', 'Cloudy'],
    'temperature': [25, 18, 28, 22],
    'humidity': [60, 80, 55, 70]
})

print("날씨 데이터:")
display(weather_data)

날씨 데이터:

   date weather  temperature  humidity
0   Fri   Sunny           25        60
1   Sat   Rainy           18        80
2   Sun   Sunny           28        55
3  Thur  Cloudy           22        70

In [54]:
# 서로 다른 키 이름으로 병합
different_key_result = pd.merge(
    df[['day', 'total_bill', 'tip']],
    weather_data,
    left_on='day',
    right_on='date',
    how='left'
)
print("\n서로 다른 키 이름 병합:")
display(different_key_result[['day', 'date', 'total_bill', 'weather', 'temperature']].head())

서로 다른 키 이름 병합:

   day date  total_bill weather  temperature
0  Sun  Sun       16.99   Sunny           28
1  Sun  Sun       10.34   Sunny           28
2  Sun  Sun       21.01   Sunny           28
3  Sun  Sun       23.68   Sunny           28
4  Sun  Sun       24.59   Sunny           28

#### 5-4. Join과 Concat 함수

In [55]:
# join() 함수 활용
df_indexed = df.set_index('day')[['total_bill', 'tip']].head(5)
weather_indexed = weather_data.set_index('date')[['weather', 'temperature']]
print('df_indexed')
display(df_indexed)
print('weather_indexed')
display(weather_indexed)

df_indexed

     total_bill   tip
day
Sun       16.99  1.01
Sun       10.34  1.66
Sun       21.01  3.50
Sun       23.68  3.31
Sun       24.59  3.61

weather_indexed

     weather  temperature
date
Fri    Sunny           25
Sat    Rainy           18
Sun    Sunny           28
Thur  Cloudy           22

In [56]:
print("1. join() 함수:")
join_result = df_indexed.join(weather_indexed)
display(join_result)

1. join() 함수:

     total_bill   tip weather  temperature
Sun       16.99  1.01   Sunny           28
Sun       10.34  1.66   Sunny           28
Sun       21.01  3.50   Sunny           28
Sun       23.68  3.31   Sunny           28
Sun       24.59  3.61   Sunny           28

In [57]:
# concat() 함수 활용
print("\n2. concat() 함수:")

# 행 방향 연결
df1_sample = df.head(5)[['total_bill', 'tip', 'day']]
df2_sample = df.tail(5)[['total_bill', 'tip', 'day']]
concat_rows = pd.concat([df1_sample, df2_sample], ignore_index=True)
print("행 방향 연결:")
display(concat_rows)

2. concat() 함수:
행 방향 연결:

   total_bill   tip   day
0       16.99  1.01   Sun
1       10.34  1.66   Sun
2       21.01  3.50   Sun
3       23.68  3.31   Sun
4       24.59  3.61   Sun
5       29.03  5.92   Sat
6       27.18  2.00   Sat
7       22.67  2.00   Sat
8       17.82  1.75   Sat
9       18.78  3.00  Thur

In [58]:
# 열 방향 연결
df_left = df[['total_bill', 'tip']].head(5)
df_right = df[['day', 'time', 'size']].head(5)
concat_cols = pd.concat([df_left, df_right], axis=1)
print("\n열 방향 연결:")
display(concat_cols)

열 방향 연결:

   total_bill   tip  day    time  size
0       16.99  1.01  Sun  Dinner     2
1       10.34  1.66  Sun  Dinner     3
2       21.01  3.50  Sun  Dinner     3
3       23.68  3.31  Sun  Dinner     2
4       24.59  3.61  Sun  Dinner     4

#### 5-5. 종합 실습

In [59]:
# 종합 실습: 레스토랑 데이터 분석
print("=== 종합 실습: 레스토랑 데이터 분석 ===")

# 1. 멀티 인덱스로 데이터 구조화
multi_analysis = df.set_index(['day', 'time', 'smoker'])
display(multi_analysis.head())

=== 종합 실습: 레스토랑 데이터 분석 ===

                   total_bill   tip     sex  size  tip_ratio_to_group_mean  \
day time   smoker
Sun Dinner No           16.99  1.01  Female     2                 0.310279
           No           10.34  1.66    Male     3                 0.509964
           No           21.01  3.50    Male     3                 1.075225
           No           23.68  3.31    Male     2                 1.016856
           No           24.59  3.61  Female     4                 1.109018

                   tip_zscore  tip_rank_in_day  tip_cumsum_in_day
day time   smoker
Sun Dinner No       -1.818097              1.0               1.01
           No       -1.291730              6.0               2.67
           No        0.198293             46.0               6.17
           No        0.044432             41.0               9.48
           No        0.287371             52.0              13.09

In [60]:
# 2. 그룹별 상세 분석
comprehensive_analysis = df.groupby(['day', 'smoker']).agg({
    'total_bill': ['count', 'mean', 'sum'],
    'tip': ['mean', 'std'],
    'size': ['mean', 'max']
}).round(2)

print("1. 종합 그룹 분석:")
display(comprehensive_analysis)

1. 종합 그룹 분석:

            total_bill                   tip        size
                 count   mean      sum  mean   std  mean max
day  smoker
Thur Yes            17  19.19   326.24  3.03  1.11  2.35   4
     No             45  17.11   770.09  2.67  1.28  2.49   6
Fri  Yes            15  16.81   252.20  2.71  1.08  2.07   4
     No              4  18.42    73.68  2.81  0.90  2.25   3
Sat  Yes            42  21.28   893.62  2.88  1.63  2.48   5
     No             45  19.66   884.78  3.10  1.64  2.56   4
Sun  Yes            19  24.12   458.28  3.52  1.26  2.58   5
     No             57  20.51  1168.88  3.17  1.22  2.93   6

In [61]:
# 3. 피벗 테이블로 요약
summary_pivot = df.pivot_table(
    values=['total_bill', 'tip'],
    index='day',
    columns=['time', 'smoker'],
    aggfunc='mean',
    fill_value=0
).round(2)

print("\n2. 피벗 테이블 요약:")
display(summary_pivot)

2. 피벗 테이블 요약:

         tip                    total_bill
time   Lunch       Dinner            Lunch        Dinner
smoker   Yes    No    Yes    No        Yes     No    Yes     No
day
Thur    3.03  2.67   0.00  3.00      19.19  17.08   0.00  18.78
Fri     2.28  3.00   3.00  2.75      12.32  15.98  19.81  19.23
Sat     0.00  0.00   2.88  3.10       0.00   0.00  21.28  19.66
Sun     0.00  0.00   3.52  3.17       0.00   0.00  24.12  20.51

In [62]:
# 4. 변환 및 정규화
df_normalized = df.copy()
df_normalized['tip_normalized'] = df.groupby('day')['tip'].transform(
    lambda x: (x - x.mean()) / x.std()
)
df_normalized['bill_rank'] = df.groupby('day')['total_bill'].transform('rank')

print("\n3. 정규화 및 순위 결과:")
display(df_normalized[['day', 'tip', 'tip_normalized', 'total_bill', 'bill_rank']].head(10))

print("\n=== 실습 완료 ===")

3. 정규화 및 순위 결과:

   day   tip  tip_normalized  total_bill  bill_rank
0  Sun  1.01       -1.818097       16.99       28.0
1  Sun  1.66       -1.291730       10.34        9.0
2  Sun  3.50        0.198293       21.01       43.0
3  Sun  3.31        0.044432       23.68       50.0
4  Sun  3.61        0.287371       24.59       54.0
5  Sun  4.71        1.178145       25.29       56.0
6  Sun  2.00       -1.016399        8.77        2.0
7  Sun  3.12       -0.109429       26.88       59.0
8  Sun  1.96       -1.048791       15.04       20.0
9  Sun  3.23       -0.020351       14.78       18.0

=== 실습 완료 ===