# 1일차 판다스 실습 (2026.07.14.)

## 2024년 6월 서울시 지하철호선별 역별 승하차 인원 정보
- 데이터: https://data.seoul.go.kr/dataList/OA-12914/S/1/datasetView.do
- 2024년 6월 데이터

#### 실습 문제
1. 2024년 6월 서울시 지하철 노선별 역별 승하차 인원 정보 파일을 읽어와서 데이터프레임으로 저장하세요.

2. 데이터프레임(df)의 처음과 마지막 5개의 로우를 각각 출력하세요.

3. 데이터프레임(df)이 몇 개의 로우와 행으로 이루어져 있는지 구조(shape)를 확인하세요.

4. 데이터프레임(df)의 평균, 표준편차, 사분위수 등 주요 통계 지표를 확인하세요.

5. 데이터프레임(df)에 몇 개의 컬럼이 있는지, 각 컬럼에 포함된 데이터들의 타입은 무엇인지 확인해보세요.

6. ‘노선명’ 컬럼이 가지고 있는 데이터의 종류를 확인하세요.

7. ‘노선명’ 컬럼의 각 데이터가 몇 개씩 포함되어 있는지 확인하세요.

8. ‘승차총승객수’ 컬럼을 기준으로 데이터를 정렬하세요.

9. ‘노선명’ 컬럼을 선택하세요.

10. 데이터프레임의 위에서부터 10개(0번째부터 9번째)의 데이터(로우)를 선택하세요.

11. 데이터프레임에서 ‘노선명’이 ‘2호선’인 로우만 선택하세요.

12. 데이터프레임에서 ‘승차총승객수’가 50,000명 이상인 로우의 ‘역명’을 선택하세요.

13. '승차총승객수'의 최대값과 최대값 로우의 인덱스가 무엇인지 확인하세요.

14. 데이터프레임에서 ‘등록일자’ 컬럼을 삭제하세요.

15. ‘승차총승객수’와 ‘하차총승객수’ 컬럼의 차이를 계산한 ‘승하차총승객수차이’ 컬럼을 생성하세요.

16. ‘승하차총승객수차이’의 평균값을 계산하세요.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import seaborn as sns

#### 1. 2024년 6월 서울시 지하철노선별 역별 승하차 인원 정보 파일을 읽어와서 데이터프레임으로 저장하세요.
- dataload

In [ ]:
subway_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CARD_SUBWAY_MONTH_202406.csv', index_col=False)
subway_df

           사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자
0      20240601  경부선   신도림    3746    4163  20240604
1      20240601  3호선    신사   24723   26535  20240604
2      20240601  3호선   압구정   26592   28521  20240604
3      20240601  3호선    옥수    8041    8143  20240604
4      20240601  3호선    금호    6886    6157  20240604
...         ...  ...   ...     ...     ...       ...
18483  20240630  1호선  종로5가   10300   10051  20240703
18484  20240630  1호선  종로3가   13891   12445  20240703
18485  20240630  1호선    종각   13202   12034  20240703
18486  20240630  1호선    시청    9389    8758  20240703
18487  20240630  1호선   서울역   35724   33895  20240703

[18488 rows x 6 columns]

#### 2. 데이터프레임(df)의 처음과 마지막 5개의 로우를 각각 출력하세요.
- `head` and `tail`

In [5]:
# 처음 5개 행 출력
subway_df.head(5)

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20240601  경부선  신도림    3746    4163  20240604
1  20240601  3호선   신사   24723   26535  20240604
2  20240601  3호선  압구정   26592   28521  20240604
3  20240601  3호선   옥수    8041    8143  20240604
4  20240601  3호선   금호    6886    6157  20240604

In [6]:
# 마지막 5개 행 출력
subway_df.tail(5)

           사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자
18483  20240630  1호선  종로5가   10300   10051  20240703
18484  20240630  1호선  종로3가   13891   12445  20240703
18485  20240630  1호선    종각   13202   12034  20240703
18486  20240630  1호선    시청    9389    8758  20240703
18487  20240630  1호선   서울역   35724   33895  20240703

#### 3. 데이터프레임(df)이 몇 개의 로우와 행으로 이루어져 있는지 구조(shape)를 확인하세요.
- `shape`

In [7]:
df_shape = subway_df.shape
df_shape

(18488, 6)

#### 4. 데이터프레임(df)의 평균, 표준편차, 사분위수 등 주요 통계 지표를 확인하세요.
- `describe`

In [8]:
df_stats = subway_df.describe()
df_stats

               사용일자        승차총승객수        하차총승객수          등록일자
count  1.848800e+04  18488.000000  18488.000000  1.848800e+04
mean   2.024062e+07  11173.348550  11120.065015  2.024063e+07
std    8.656671e+00  11092.504508  11287.307848  2.655875e+01
min    2.024060e+07      1.000000      0.000000  2.024060e+07
25%    2.024061e+07   3872.750000   3774.750000  2.024061e+07
50%    2.024062e+07   8023.000000   7738.500000  2.024062e+07
75%    2.024062e+07  14810.500000  14498.250000  2.024063e+07
max    2.024063e+07  96129.000000  97882.000000  2.024070e+07

#### 5. 데이터프레임(df)에 몇 개의 컬럼이 있는지, 각 컬럼에 포함된 데이터들의 타입은 무엇인지 확인해보세요.
- `info`

In [9]:
df_info = subway_df.info()
df_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18488 entries, 0 to 18487
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    18488 non-null  int64
 1   노선명     18488 non-null  object
 2   역명      18488 non-null  object
 3   승차총승객수  18488 non-null  int64
 4   하차총승객수  18488 non-null  int64
 5   등록일자    18488 non-null  int64
dtypes: int64(4), object(2)
memory usage: 866.8+ KB

#### 6. ‘노선명’ 컬럼이 가지고 있는 데이터의 종류를 확인하세요.
- `unique`

In [10]:
unique_lines = subway_df['노선명'].unique()
unique_lines

array(['경부선', '3호선', '1호선', '2호선', '중앙선', '우이신설선', '7호선', '경원선', '안산선',
       '신림선', '수인선', '서해선', '분당선', '과천선', '공항철도 1호선', '경춘선', '경인선', '경의선',
       '경강선', '9호선2~3단계', '9호선', '8호선', '일산선', '장항선', '6호선', '5호선', '4호선'],
      dtype=object)

#### 7. ‘노선명’ 컬럼의 각 데이터가 몇 개씩 포함되어 있는지 확인하세요.
- `value_counts`

In [11]:
line_counts = subway_df['노선명'].value_counts()
line_counts

노선명
5호선         1680
2호선         1500
7호선         1264
경부선         1170
6호선         1146
분당선         1050
3호선         1020
경원선          990
경의선          813
4호선          780
9호선          750
중앙선          630
경인선          600
경춘선          570
8호선          540
수인선          540
공항철도 1호선     420
우이신설선        390
안산선          390
9호선2~3단계     390
경강선          360
신림선          330
일산선          325
1호선          300
과천선          240
장항선          210
서해선           90
Name: count, dtype: int64

#### 8. ‘승차총승객수’ 컬럼을 기준으로 데이터를 정렬하세요.
- `sort_values`

In [12]:
df_sorted_by_ridership = subway_df.sort_values(by='승차총승객수')
df_sorted_by_ridership

           사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자
18406  20240630  일산선    지축       1       0  20240703
4097   20240607  경의선  김포공항       1       0  20240610
515    20240601  6호선   연신내       1       0  20240604
10859  20240618  7호선  부평구청       1       0  20240621
2211   20240604  7호선  부평구청       1       0  20240607
...         ...  ...   ...     ...     ...       ...
15843  20240626  2호선    강남   92151   90073  20240629
16562  20240627  2호선    강남   92776   89977  20240630
8186   20240614  2호선    강남   93095   92090  20240617
12327  20240621  2호선    강남   94871   93540  20240624
17222  20240628  2호선    강남   96129   95486  20240701

[18488 rows x 6 columns]

#### 9. ‘노선명’ 컬럼을 선택하세요.

In [13]:
line_column = subway_df['노선명']
line_column

0        경부선
1        3호선
2        3호선
3        3호선
4        3호선
        ...
18483    1호선
18484    1호선
18485    1호선
18486    1호선
18487    1호선
Name: 노선명, Length: 18488, dtype: object

#### 10. 데이터프레임의 위에서부터 10개(0번째부터 9번째)의 데이터(로우)를 선택하세요.
- `iloc`

In [14]:
first_10_rows = subway_df.iloc[:10]
first_10_rows

       사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자
0  20240601  경부선    신도림    3746    4163  20240604
1  20240601  3호선     신사   24723   26535  20240604
2  20240601  3호선    압구정   26592   28521  20240604
3  20240601  3호선     옥수    8041    8143  20240604
4  20240601  3호선     금호    6886    6157  20240604
5  20240601  3호선     약수   10863   10243  20240604
6  20240601  3호선   동대입구   11493   13231  20240604
7  20240601  3호선    충무로      14       0  20240604
8  20240601  3호선  을지로3가    8536    8812  20240604
9  20240601  3호선     안국   26860   29280  20240604

#### 11. 데이터프레임에서 ‘노선명’이 ‘2호선’인 로우만 선택하세요.
- filtering

In [15]:
line_2_df = subway_df[subway_df['노선명'] == '2호선']
line_2_df

           사용일자  노선명              역명  승차총승객수  하차총승객수      등록일자
20     20240601  2호선              시청   19669   15817  20240604
21     20240601  2호선           을지로입구   45898   45464  20240604
22     20240601  2호선           을지로3가   18865   17121  20240604
23     20240601  2호선           을지로4가   10354   11323  20240604
24     20240601  2호선  동대문역사문화공원(DDP)   15466   17867  20240604
...         ...  ...             ...     ...     ...       ...
18473  20240630  2호선  동대문역사문화공원(DDP)   10396   12978  20240703
18474  20240630  2호선           을지로4가    5468    5447  20240703
18475  20240630  2호선           을지로3가   11046   10669  20240703
18476  20240630  2호선           을지로입구   24319   23677  20240703
18477  20240630  2호선              시청    7912    6312  20240703

[1500 rows x 6 columns]

#### 12. 데이터프레임에서 ‘승차총승객수’가 50,000명 이상인 로우의 ‘역명’을 선택하세요.
- filtering

In [16]:
stations_above_50000 = subway_df[subway_df['승차총승객수'] >= 50000]['역명']
stations_above_50000.unique()

array(['잠실(송파구청)', '강남', '홍대입구', '서울역', '고속터미널', '가산디지털단지', '신림', '역삼',
       '선릉', '삼성(무역센터)', '을지로입구', '구로디지털단지', '신도림', '서울대입구(관악구청)', '용산',
       '성수'], dtype=object)

#### 13. '승차총승객수'의 최대값과 최대값 로우의 인덱스가 무엇인지 확인하세요.
- `max` and `idxmax`

In [17]:
max_ridership = subway_df['승차총승객수'].max()
print(f'승차 총 승객수의 최대값: {max_ridership:,}')

승차 총 승객수의 최대값: 96,129

In [18]:
max_ridership_index = subway_df['승차총승객수'].idxmax()
print(f'승차 총 승객수의 최대값의 인덱스: {max_ridership_index:,}')

승차 총 승객수의 최대값의 인덱스: 17,222

#### 14. 데이터프레임에서 0번 로우를 삭제하세요.
- `drop`

In [19]:
subway_df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20240601  경부선  신도림    3746    4163  20240604
1  20240601  3호선   신사   24723   26535  20240604
2  20240601  3호선  압구정   26592   28521  20240604
3  20240601  3호선   옥수    8041    8143  20240604
4  20240601  3호선   금호    6886    6157  20240604

In [20]:
df_dropped_row_0 = subway_df.drop(0)
df_dropped_row_0.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
1  20240601  3호선   신사   24723   26535  20240604
2  20240601  3호선  압구정   26592   28521  20240604
3  20240601  3호선   옥수    8041    8143  20240604
4  20240601  3호선   금호    6886    6157  20240604
5  20240601  3호선   약수   10863   10243  20240604

#### 15. 데이터프레임에서 ‘등록일자’ 컬럼을 삭제하세요.
- `drop`

In [21]:
df_dropped_column = subway_df.drop(columns=['등록일자'])
df_dropped_column

           사용일자  노선명    역명  승차총승객수  하차총승객수
0      20240601  경부선   신도림    3746    4163
1      20240601  3호선    신사   24723   26535
2      20240601  3호선   압구정   26592   28521
3      20240601  3호선    옥수    8041    8143
4      20240601  3호선    금호    6886    6157
...         ...  ...   ...     ...     ...
18483  20240630  1호선  종로5가   10300   10051
18484  20240630  1호선  종로3가   13891   12445
18485  20240630  1호선    종각   13202   12034
18486  20240630  1호선    시청    9389    8758
18487  20240630  1호선   서울역   35724   33895

[18488 rows x 5 columns]

In [22]:
df_dropped_column['등록일자']

KeyError: '등록일자'

#### 16. ‘승차총승객수’ 컬럼의 모든 값을 2씩 증가시키세요.

In [ ]:
subway_df

           사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자
0      20240601  경부선   신도림    3746    4163  20240604
1      20240601  3호선    신사   24723   26535  20240604
2      20240601  3호선   압구정   26592   28521  20240604
3      20240601  3호선    옥수    8041    8143  20240604
4      20240601  3호선    금호    6886    6157  20240604
...         ...  ...   ...     ...     ...       ...
18483  20240630  1호선  종로5가   10300   10051  20240703
18484  20240630  1호선  종로3가   13891   12445  20240703
18485  20240630  1호선    종각   13202   12034  20240703
18486  20240630  1호선    시청    9389    8758  20240703
18487  20240630  1호선   서울역   35724   33895  20240703

[18488 rows x 6 columns]

In [ ]:
subway_df['승차총승객수'] += 2
subway_df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20240601  경부선  신도림    3748    4163  20240604
1  20240601  3호선   신사   24725   26535  20240604
2  20240601  3호선  압구정   26594   28521  20240604
3  20240601  3호선   옥수    8043    8143  20240604
4  20240601  3호선   금호    6888    6157  20240604

#### 17. ‘승차총승객수’와 ‘하차총승객수’ 컬럼의 차이를 계산한 ‘승하차총승객수차이’ 컬럼을 생성하세요.

In [23]:
subway_df['승하차총승객수차이'] = subway_df['승차총승객수'] - subway_df['하차총승객수']
subway_df

           사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자  승하차총승객수차이
0      20240601  경부선   신도림    3746    4163  20240604       -417
1      20240601  3호선    신사   24723   26535  20240604      -1812
2      20240601  3호선   압구정   26592   28521  20240604      -1929
3      20240601  3호선    옥수    8041    8143  20240604       -102
4      20240601  3호선    금호    6886    6157  20240604        729
...         ...  ...   ...     ...     ...       ...        ...
18483  20240630  1호선  종로5가   10300   10051  20240703        249
18484  20240630  1호선  종로3가   13891   12445  20240703       1446
18485  20240630  1호선    종각   13202   12034  20240703       1168
18486  20240630  1호선    시청    9389    8758  20240703        631
18487  20240630  1호선   서울역   35724   33895  20240703       1829

[18488 rows x 7 columns]

#### 18. ‘승하차총승객수차이’의 평균값을 계산하세요.
- `mean`

In [24]:
mean_difference = subway_df['승하차총승객수차이'].mean()
print(f'승하차 총 승객수 차이의 평균: {mean_difference:.4}')

승하차 총 승객수 차이의 평균: 53.28

#### 19. 데이터프레임에서 10개의 행을 샘플링하세요.
- `sample`

In [25]:
sample_df = subway_df.sample(10)
sample_df

           사용일자       노선명          역명  승차총승객수  하차총승객수      등록일자  승하차총승객수차이
1637   20240603       7호선  온수(성공회대입구)   11833   10925  20240606        908
15062  20240625       장항선          배방    1401    1308  20240628         93
4058   20240607       경원선          녹양    4772    4506  20240610        266
2461   20240604       2호선    삼성(무역센터)   62475   64434  20240607      -1959
6368   20240611       2호선          아현   12331   11469  20240614        862
8486   20240614       경부선          구로   19553   20235  20240617       -682
2161   20240604  9호선2~3단계        석촌고분    7883    7698  20240607        185
13811  20240623       4호선  한성대입구(삼선교)    8673    8549  20240626        124
15973  20240626       5호선          명일    9916   10416  20240629       -500
16518  20240627       중앙선         운길산     703     707  20240630         -4

#### 20. 샘플링된 데이터프레임(sample_df)의 값에서 ‘노선명’ 컬럼의 값이 1호선, 2호선, 3호선, 4호선인  값을 영어(line1, line2, line3, line4)로 변경하세요.
- `replace`

In [26]:
sample_df['노선명'].replace({'1호선': 'line1', '2호선': 'line2', '3호선': 'line3', '4호선': 'line4'}, inplace=True)
sample_df

/tmp/ipykernel_2814219/1060468851.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_df['노선명'].replace({'1호선': 'line1', '2호선': 'line2', '3호선': 'line3', '4호선': 'line4'}, inplace=True)

           사용일자       노선명          역명  승차총승객수  하차총승객수      등록일자  승하차총승객수차이
1637   20240603       7호선  온수(성공회대입구)   11833   10925  20240606        908
15062  20240625       장항선          배방    1401    1308  20240628         93
4058   20240607       경원선          녹양    4772    4506  20240610        266
2461   20240604     line2    삼성(무역센터)   62475   64434  20240607      -1959
6368   20240611     line2          아현   12331   11469  20240614        862
8486   20240614       경부선          구로   19553   20235  20240617       -682
2161   20240604  9호선2~3단계        석촌고분    7883    7698  20240607        185
13811  20240623     line4  한성대입구(삼선교)    8673    8549  20240626        124
15973  20240626       5호선          명일    9916   10416  20240629       -500
16518  20240627       중앙선         운길산     703     707  20240630         -4

#### 21. 데이터프레임(df)의 ‘사용일자’ 컬럼을 연도-월-일(예: 2021-02-01)의 형태로 표시되도록 수정하세요.
- `to_datetime`

In [27]:
subway_df['사용일자'] = pd.to_datetime(subway_df['사용일자'], format='%Y%m%d').dt.strftime('%Y-%m-%d')
subway_df

             사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자  승하차총승객수차이
0      2024-06-01  경부선   신도림    3746    4163  20240604       -417
1      2024-06-01  3호선    신사   24723   26535  20240604      -1812
2      2024-06-01  3호선   압구정   26592   28521  20240604      -1929
3      2024-06-01  3호선    옥수    8041    8143  20240604       -102
4      2024-06-01  3호선    금호    6886    6157  20240604        729
...           ...  ...   ...     ...     ...       ...        ...
18483  2024-06-30  1호선  종로5가   10300   10051  20240703        249
18484  2024-06-30  1호선  종로3가   13891   12445  20240703       1446
18485  2024-06-30  1호선    종각   13202   12034  20240703       1168
18486  2024-06-30  1호선    시청    9389    8758  20240703        631
18487  2024-06-30  1호선   서울역   35724   33895  20240703       1829

[18488 rows x 7 columns]

#### 22. 데이터프레임(df)의 ‘사용일자1’ 컬럼을 새로 생성하고, ‘사용일자’ 컬럼에 있는 값을 datetime64의 타입으로 변환하여 저장하세요.
- `to_datetime`

In [28]:
subway_df['사용일자1'] = pd.to_datetime(subway_df['사용일자'], format='%Y-%m-%d')
subway_df

             사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자  승하차총승객수차이      사용일자1
0      2024-06-01  경부선   신도림    3746    4163  20240604       -417 2024-06-01
1      2024-06-01  3호선    신사   24723   26535  20240604      -1812 2024-06-01
2      2024-06-01  3호선   압구정   26592   28521  20240604      -1929 2024-06-01
3      2024-06-01  3호선    옥수    8041    8143  20240604       -102 2024-06-01
4      2024-06-01  3호선    금호    6886    6157  20240604        729 2024-06-01
...           ...  ...   ...     ...     ...       ...        ...        ...
18483  2024-06-30  1호선  종로5가   10300   10051  20240703        249 2024-06-30
18484  2024-06-30  1호선  종로3가   13891   12445  20240703       1446 2024-06-30
18485  2024-06-30  1호선    종각   13202   12034  20240703       1168 2024-06-30
18486  2024-06-30  1호선    시청    9389    8758  20240703        631 2024-06-30
18487  2024-06-30  1호선   서울역   35724   33895  20240703       1829 2024-06-30

[18488 rows x 8 columns]

#### 23. ‘노선명’을 기준으로 데이터를 그룹화하고, 각 그룹의 ‘승차총승객수’와 ‘하차총승객수’의 합, 평균, 표준편차를 구하세요.
- `groupby` and `agg`

In [29]:
grouped = subway_df.groupby('노선명')[['승차총승객수', '하차총승객수']].agg(['sum', 'mean', 'std'])
grouped

            승차총승객수                                하차총승객수                \
               sum          mean           std       sum          mean
노선명
1호선        7091181  23637.270000  13494.817097   6910880  23036.266667
2호선       40211398  26807.598667  20379.529023  40834456  27222.970667
3호선       15330482  15029.884314  11612.881622  15172085  14874.593137
4호선       15206981  19496.129487  10088.430559  15542166  19925.853846
5호선       18907651  11254.554167   7405.440923  18745399  11157.975595
6호선        9922429   8658.315009   4825.095596   9771109   8526.273124
7호선       17038906  13480.147152   7272.544820  16732458  13237.704114
8호선        5577170  10328.092593   5519.824428   5576864  10327.525926
9호선        8212394  10949.858667   8875.727754   8285968  11047.957333
9호선2~3단계   3129010   8023.102564   5245.234713   3108735   7971.115385
경강선         990469   2751.302778   2049.626746    958504   2662.511111
경부선       13668081  11682.120513  10690.740191  13515493  11551.703419
경원선        6086113   6147.588889   4979.127152   5863279   5922.504040
경의선        3481080   4281.771218   3047.645163   3398315   4179.969250
경인선        7993038  13321.730000   9027.045806   7798088  12996.813333
경춘선        1181032   2071.985965   1570.108704   1130116   1982.659649
공항철도 1호선   3887874   9256.842857   4879.180395   3641473   8670.173810
과천선        3069977  12791.570833   9046.446429   3040087  12667.029167
분당선       10710946  10200.900952   6516.597576  11066631  10539.648571
서해선         305134   3390.377778   1114.135989    313246   3480.511111
수인선        1853518   3432.440741   2122.019158   1804724   3342.081481
신림선        1314209   3982.451515   2408.473636   1293199   3918.784848
안산선        3532345   9057.294872   5235.612153   3513919   9010.048718
우이신설선      1385340   3552.153846   1539.329408   1333500   3419.230769
일산선        3188969   9812.212308   5579.444107   3058858   9411.870769
장항선         552036   2628.742857   1481.068608    527927   2513.938095
중앙선        2745105   4357.309524   6106.976665   2650283   4206.798413


                   std
노선명
1호선       12944.494942
2호선       20666.553028
3호선       11712.023257
4호선       10293.297475
5호선        7575.838977
6호선        4936.113772
7호선        7522.308452
8호선        5691.312638
9호선        9021.378192
9호선2~3단계   5445.674604
경강선        1979.551623
경부선       11150.520037
경원선        5067.888120
경의선        2992.163124
경인선        9235.487819
경춘선        1517.298391
공항철도 1호선   4519.019374
과천선        9254.981253
분당선        7065.467438
서해선        1263.658673
수인선        1997.399971
신림선        2264.398004
안산선        5559.750297
우이신설선      1453.740175
일산선        5420.661524
장항선        1430.997799
중앙선        5838.507333

#### 24. ‘승차총승객수’ 컬럼의 값이 100,000 이상인 경우 ‘high’, 그렇지 않은 경우 ‘low’로 표시하는 새로운 컬럼 ‘승차레벨’을 추가하세요.
- `apply`

In [30]:
subway_df['승차레벨'] = subway_df['승차총승객수'].apply(lambda x: 'high' if x >= 100000 else 'low')
subway_df[['승차총승객수', '승차레벨']]

       승차총승객수 승차레벨
0        3746  low
1       24723  low
2       26592  low
3        8041  low
4        6886  low
...       ...  ...
18483   10300  low
18484   13891  low
18485   13202  low
18486    9389  low
18487   35724  low

[18488 rows x 2 columns]

#### 25. ‘노선명’ 컬럼의 값에 대해 map 함수를 사용하여 영어로 변환된 값을 가진 새로운 컬럼 ‘노선명_영어’를 추가하세요.
- `map`

In [31]:
line_name_map = {
    '1호선': 'Line 1',
    '2호선': 'Line 2',
    '3호선': 'Line 3',
    '4호선': 'Line 4',
    '5호선': 'Line 5',
    '6호선': 'Line 6',
    '7호선': 'Line 7',
    '8호선': 'Line 8',
    '9호선': 'Line 9',
}
subway_df['노선명_영어'] = subway_df['노선명'].map(line_name_map)
subway_df[['노선명', '노선명_영어']]

       노선명  노선명_영어
0      경부선     NaN
1      3호선  Line 3
2      3호선  Line 3
3      3호선  Line 3
4      3호선  Line 3
...    ...     ...
18483  1호선  Line 1
18484  1호선  Line 1
18485  1호선  Line 1
18486  1호선  Line 1
18487  1호선  Line 1

[18488 rows x 2 columns]

#### 26. '노선명'과 '역명'을 멀티 인덱스로 설정하고, 해당 구조에서 특정 노선의 모든 역 데이터를 추출하세요.

`set_index`, `loc`, `xs()`, `sort_index`

In [32]:
multi_index_df = subway_df.set_index(['노선명', '역명']).sort_index()
line2_data = multi_index_df.loc['2호선']
line2_data.head()

          사용일자  승차총승객수  하차총승객수      등록일자  승하차총승객수차이      사용일자1 승차레벨  노선명_영어
역명
강남  2024-06-01   61572   60770  20240604        802 2024-06-01  low  Line 2
강남  2024-06-02   34043   32607  20240605       1436 2024-06-02  low  Line 2
강남  2024-06-03   85514   83567  20240606       1947 2024-06-03  low  Line 2
강남  2024-06-04   88454   86571  20240607       1883 2024-06-04  low  Line 2
강남  2024-06-05   91419   90426  20240608        993 2024-06-05  low  Line 2

#### 27. ‘노선명’을 행으로, 사용일자1의 요일(weekday)을 열로 하여 승차총승객수 평균을 가진 피벗 테이블 생성하기

`pivot_table`

In [33]:
subway_df['요일'] = subway_df['사용일자1'].dt.day_name()
pivot_table = subway_df.pivot_table(values='승차총승객수',
                           index='노선명',
                           columns='요일',
                           aggfunc='mean',
                           fill_value=0)
pivot_table

요일,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
노선명,,,,,,,
1호선,27458.925000,25861.150000,21315.420000,15436.900000,24910.825000,26435.975000,26672.250000
2호선,31837.415000,29850.550000,22367.724000,16258.188000,28384.980000,31125.420000,31576.235000
3호선,17891.970588,16809.007353,12765.817647,9150.200000,15770.801471,17280.323529,17577.007353
4호선,22662.980769,21409.375000,17025.530769,12573.130769,20550.269231,22135.557692,22464.461538
5호선,13349.245536,12978.093750,8910.864286,6530.214286,11946.674107,13331.714286,13502.080357
6호선,10016.222222,9624.875817,7228.296875,5414.442708,9114.894737,10204.625000,10219.526316
7호선,15760.482353,15819.869048,10574.095238,7728.128571,14340.880952,15976.100000,16269.130952
8호선,12228.430556,11964.944444,8123.600000,5944.122222,10927.875000,12277.763889,12477.027778
9호선,13140.660000,12557.810000,8509.160000,6342.344000,11772.240000,12962.360000,13126.490000
9호선2~3단계,9318.846154,8957.692308,6706.215385,4951.415385,8409.923077,9403.961538,9510.807692
경강선,3214.812500,3050.916667,2359.700000,1852.216667,2832.208333,3103.458333,3168.479167
경부선,13287.346154,12541.903846,10725.169231,8653.923077,11877.910256,12684.192308,13000.685897
경원선,6914.507576,6678.454545,5550.975758,4461.581818,6331.083333,6800.954545,6866.219697
경의선,4947.385321,4934.568807,3529.488889,2607.911765,4504.037037,5034.703704,5024.129630
경인선,15196.412500,14714.650000,11832.250000,9186.660000,13681.050000,14913.537500,15133.687500
경춘선,2321.592105,2261.697368,1808.484211,1583.873684,2167.078947,2275.421053,2273.657895
공항철도 1호선,10643.642857,9973.410714,8261.257143,6984.871429,9596.517857,10061.303571,10093.785714
과천선,15055.125000,13726.218750,11280.950000,9177.250000,12830.156250,14311.125000,14441.406250
분당선,12221.871429,11727.371429,8162.697143,5869.925714,10681.542857,12090.642857,12244.550000
서해선,3856.583333,3651.166667,3006.600000,2469.000000,3528.583333,3749.500000,3797.500000
수인선,3971.277778,3893.388889,2797.611111,2173.400000,3619.444444,3966.083333,4079.347222
신림선,4636.750000,4605.272727,3095.309091,2468.872727,4212.022727,4740.659091,4718.454545
안산선,10277.846154,10075.307692,7946.030769,6355.276923,9242.769231,10158.788462,10298.365385
우이신설선,3994.038462,3949.019231,3007.415385,2471.492308,3725.980769,4068.076923,4055.403846
일산선,11538.116279,11530.761905,8013.145455,6063.444444,10114.590909,11236.590909,11649.697674
장항선,3023.035714,2872.607143,2358.942857,2030.742857,2557.392857,2832.607143,2942.821429
중앙선,4925.857143,4871.595238,3771.447619,2967.428571,4557.619048,4948.071429,4953.083333

#### 29. 28번에서 만든 피벗 테이블을 stack하여 긴 형태(Long form)로 변환하기

`stack`, `reset_index`

In [34]:
stacked_data = pivot_table.stack()
stacked_df = stacked_data.reset_index()
stacked_df.columns = ['노선명', '요일', '평균승차인원']
stacked_df.head()

   노선명        요일     평균승차인원
0  1호선    Friday  27458.925
1  1호선    Monday  25861.150
2  1호선  Saturday  21315.420
3  1호선    Sunday  15436.900
4  1호선  Thursday  24910.825

#### 29. 승차총승객수와 하차총승객수 컬럼을 melt를 이용해 ‘구분’(승차/하차)과 ‘인원’ 컬럼으로 변환하기

`melt`

In [35]:
melted_data = pd.melt(subway_df,
                     id_vars=['노선명', '역명', '사용일자1'],
                     value_vars=['승차총승객수', '하차총승객수'],
                     var_name='구분',
                     value_name='인원')
melted_data['구분'] = melted_data['구분'].map({
    '승차총승객수': '승차',
    '하차총승객수': '하차'
})

melted_data.head()

   노선명   역명      사용일자1  구분     인원
0  경부선  신도림 2024-06-01  승차   3746
1  3호선   신사 2024-06-01  승차  24723
2  3호선  압구정 2024-06-01  승차  26592
3  3호선   옥수 2024-06-01  승차   8041
4  3호선   금호 2024-06-01  승차   6886

#### 30. 27번에서 생성한 멀티 인덱스의 레벨 순서를 바꾸고, 특정 레벨을 제거한 후 xs 함수로 데이터를 추출하세요.

`swaplevel`, `droplevel`, `xs`

In [36]:
multi_index_df = subway_df.set_index(['노선명', '역명'])
swapped_df = multi_index_df.swaplevel(0, 1).sort_index()
dropped_df = swapped_df.droplevel('노선명')
gangnam_data = swapped_df.xs('강남', level='역명')
print("레벨 순서 변경:")
display(swapped_df.head())
print("강남역 데이터:") 
display(gangnam_data.head())

레벨 순서 변경:

                      사용일자  승차총승객수  하차총승객수      등록일자  승하차총승객수차이      사용일자1  \
역명       노선명
4.19민주묘지 우이신설선  2024-06-01    2949    2625  20240604        324 2024-06-01
         우이신설선  2024-06-02    2440    2170  20240605        270 2024-06-02
         우이신설선  2024-06-03    4676    4846  20240606       -170 2024-06-03
         우이신설선  2024-06-04    4877    4774  20240607        103 2024-06-04
         우이신설선  2024-06-05    4993    4772  20240608        221 2024-06-05

               승차레벨 노선명_영어         요일
역명       노선명
4.19민주묘지 우이신설선  low    NaN   Saturday
         우이신설선  low    NaN     Sunday
         우이신설선  low    NaN     Monday
         우이신설선  low    NaN    Tuesday
         우이신설선  low    NaN  Wednesday

강남역 데이터:

,사용일자,승차총승객수,하차총승객수,등록일자,승하차총승객수차이,사용일자1,승차레벨,노선명_영어,요일
노선명,,,,,,,,,
2호선,2024-06-01,61572,60770,20240604,802,2024-06-01,low,Line 2,Saturday
2호선,2024-06-02,34043,32607,20240605,1436,2024-06-02,low,Line 2,Sunday
2호선,2024-06-03,85514,83567,20240606,1947,2024-06-03,low,Line 2,Monday
2호선,2024-06-04,88454,86571,20240607,1883,2024-06-04,low,Line 2,Tuesday
2호선,2024-06-05,91419,90426,20240608,993,2024-06-05,low,Line 2,Wednesday


#### 31. 평균 '승차총승객수'가 80,000명 이상이면서 동시에 '하차총승객수'의 표준편차가 30,000 이하인 노선 그룹만 필터링하세요.

`groupby`, `filter`, `lambda`

In [37]:
filtered_lines = subway_df.groupby('노선명').filter(
    lambda x: (x['승차총승객수'].mean() >= 80000) & 
              (x['하차총승객수'].std() <= 30000)
)

print(f"필터링된 노선:) {filtered_lines['노선명'].unique()}")
print(f"필터링된 데이터 수: {len(filtered_lines)}")

filtered_lines.head()

필터링된 노선:) []
필터링된 데이터 수: 0

Empty DataFrame
Columns: [사용일자, 노선명, 역명, 승차총승객수, 하차총승객수, 등록일자, 승하차총승객수차이, 사용일자1, 승차레벨, 노선명_영어, 요일]
Index: []

#### 32. ‘승차총승객수’를 구간별로 나누어 ‘승차구간’이라는 새로운 컬럼을 추가하세요.
- 구간은 0-50,000, 50,001-100,000, 100,001-150,000, 150,001 이상으로 설정합니다.
- `cut`

In [38]:
bins = [0, 25000, 50000, 750000, float('inf')]
labels = ['0-25K', '25K-50K', '50-75K', '75K+']
subway_df['승차구간'] = pd.cut(subway_df['승차총승객수'], bins=bins, labels=labels, right=False)
subway_df[['승차총승객수', '승차구간']]

       승차총승객수     승차구간
0        3746    0-25K
1       24723    0-25K
2       26592  25K-50K
3        8041    0-25K
4        6886    0-25K
...       ...      ...
18483   10300    0-25K
18484   13891    0-25K
18485   13202    0-25K
18486    9389    0-25K
18487   35724  25K-50K

[18488 rows x 2 columns]

In [39]:
subway_df['승차구간'].unique()

['0-25K', '25K-50K', '50-75K']
Categories (4, object): ['0-25K' < '25K-50K' < '50-75K' < '75K+']